### PR TITLE
Add gitignore and do some code splitting

### PR DESCRIPTION
**Pull request by developomp**
b30b2d89b91dc4e417f2a617ed8f3bf6f0334cce: added .gitignore
f094ee6dcf5e54e689e0690ec91b4081bee8a3f8: separated interactive widgets to separate files for readability

### CODE REVIEW

**Comment by bczsalba** [comment]
Hey there! I'm fine and probably happier than anything with these changes, but they aren't really linting proof at the moment.

One thing though: I'm not sure about the underscore in `input_field.py`. The PascalCase in the class name has been more about looks if anything, so `inputfield.py` would look and work better IMO. Feel free to dispute this part, as I'm not very attached to either.

Running `make lint` in the root of the project gives me these new errors: 
_(there is an extra on the top that is present in upstream as well, so we will ignore it)_

Screenshot 2022-01-29 at 8 42 31

Could you fix these? Since we don't have a contribution guide at the moment I'll just tell you here, for docstrings we use Google's styleguide. 

Thank you!

**Comment by developomp** [comment]
Will follow up with a fix in a couple of hours after I go for a walk.

As for the filename, I intentionally chose to use an underscore, so some IDEs won't mark it as a typo. It can be imported without mentioning the filename once (like this: `from pytermgui.widgets.interactive import InputField`) so I think it's okay as it is.

**Comment by bczsalba** [comment]
> As for the filename, I intentionally chose to use an underscore, so some IDEs won't mark it as a typo. It can be imported without mentioning the filename once (like this: from pytermgui.widgets.interactive import InputField) so I think it's okay as it is.

Fair point, I use a pretty raw Vim for my editing so that isn't something I run into.

**Comment by developomp** [comment]
Fixed all warnings introduced by the changes. Review please!

**Comment by bczsalba** [comment]
Looks good, thank you!

**Pull request merged**
