### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by UltraStudioLTD**

### CODE REVIEW

**Comment by UltraStudioLTD** [comment]
I added `__version__` back

**Comment by UltraStudioLTD** [comment]
> What exactly is the value provided by this PR?

Small performance increase

**Comment by UltraStudioLTD** [comment]
And more efficient memory management since it only imports necessary functions and variable

**Comment by bczsalba** [comment]
The whole module will be evaluated anyways due to how Python works, and the tiny amount of memory efficiency IMO is premature optimization inhibiting readability.

Also, please read and follow our CONTRIBUTING.md file next time. Your commit messages, PR title and lack of explanation don't follow the given standards.

**Comment by UltraStudioLTD** [comment]
> 

Alright. I didn't notice it before 😅

**Pull request closed without merging**
